name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.1]

    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false

    - uses: actions/checkout@v1
    - name: Set up packages
      run: |
        yarn install --frozen-lockfile

    - name: Run test
      run: |
        yarn test

    - name: Google Chat Notification
      uses: Co-qn/google-chat-notification@releases/v1
      with:
        name: Build
        url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        status: ${{ job.status }}
      if: always()
